-- MODELO DE ENTIDAD DE RELACION 1 A 1

CREATE TABLE CAMIONERO(
DNI INT PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
FECHA_NAC DATE CHECK(FECHA_NAC < GETDATE()),
MAIL VARCHAR(30) NOT NULL,
)

CREATE TABLE CAMION(
ID_CAMIONERO INT PRIMARY KEY FOREIGN KEY REFERENCES CAMIONERO(DNI),
MARCA VARCHAR(30) NOT NULL,
MODELO VARCHAR(30) NOT NULL,
AÑO_FABRICACION DATE CHECK(AÑO_FABRICACION < GETDATE())
)