CREATE TABLE CLIENTE(
DNI INT PRIMARY KEY,
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(30),
EDAD DATE NOT NULL CHECK (EDAD < GETDATE())
)

CREATE TABLE TIENDA(
N_VENTA INT PRIMARY KEY IDENTITY (1,1),
VENDEDOR VARCHAR(30) NOT NULL,
COSTO MONEY CHECK (COSTO > 0)
)

CREATE TABLE CLIENTE_TIENDA(
ID_OPERACION INT PRIMARY KEY,
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(DNI),
ID_TIENDA INT FOREIGN KEY REFERENCES TIENDA(N_VENTA)
)